# -*- coding: utf-8 -*-
"""Tower of Hanoi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zJov-47QF5fHV81_xVuD8mpJvj3cdW2
"""

def tower_of_hanoi(n, source, helper, target):
    if n == 1:
        print("Move disk 1 from", source, "to", target)
        return
    tower_of_hanoi(n-1, source, target, helper)
    print("Move disk", n, "from", source, "to", target)
    tower_of_hanoi(n-1, helper, source, target)

n = int(input("Enter the number of disks: "))
source = input("Enter the name of the source tower: ")
helper = input("Enter the name of the helper tower: ")
target = input("Enter the name of the target tower: ")

tower_of_hanoi(n, source, helper, target)